server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name_in_redirect off;
	absolute_redirect off;
	port_in_redirect off;

	root $web_root;
	index index.html index.htm;
	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}
