packages:
  - website
  - ucsc2jbrowse
  - genark2jbrowse
  - 'aws/*'
  - hubtools
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@jbrowse/add-track-core@5.0.0-beta.2 || 5.0.0-beta.7'
  - '@jbrowse/cigar-utils@5.0.0-beta.2 || 5.0.0-beta.7'
  - '@jbrowse/cli@5.0.0-beta.2 || 5.0.0-beta.7'
  - '@jbrowse/text-indexing-core@5.0.0-beta.2 || 5.0.0-beta.7'
  - p2s_mapper@1.4.0
