packages:
  - website
  - ucsc2jbrowse
  - genark2jbrowse
  - 'aws/*'
  - hubtools
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  react-msaview@5.6.3: patches/react-msaview@5.6.3.patch
