/// <reference types="vite/client" />

declare module '*.module.css' {
  const classes: Record<string, string>
  export default classes
}

declare module '*.css'

// recentlyUpdated.json is generated by `pnpm generate-recently-updated` (in
// website's `prebuild`) and gitignored, being 31MB. `astro build` always has it;
// a fresh checkout never does, so `tsc --noEmit` could not resolve the import
// and CI's typecheck failed on every push from 2026-08-02.
//
// Declared rather than generated in CI on purpose: the generator reads
// processedHubJson/all.json, which `predev` pulls from S3, and a typecheck
// should not need the network or a 31MB write to tell whether the code is
// sound. `unknown[]` rather than the row type because the consumer already
// narrows it, and this file should not become a second place the shape is
// spelled out.
declare module '*/recentlyUpdated.json' {
  const rows: unknown[]
  export default rows
}
