AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM application to fetch a JSON file from a URL

Resources:
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /list
            Method: get
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

  DbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: db.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /db
            Method: get
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://$(ServerlessRestApi).execute-api.$(AWS::Region).amazonaws.com/Prod/'
