AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM application to fetch a JSON file from a URL

Resources:
  JBrowseHubsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 120
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
    Metadata:
      BuildMethod: nodejs20.x

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt JBrowseHubsFunctionUrl.FunctionUrl
