export const hubCategories = [
  {
    id: 'primates',
    title: 'UCSC GenArk - Primates',
    description: 'NCBI primate genomes',
    tag: 'main',
  },
  {
    id: 'mammals',
    title: 'UCSC GenArk - Mammals',
    description: 'NCBI mammal genomes',
    tag: 'main',
  },
  {
    id: 'birds',
    title: 'UCSC GenArk - Birds',
    description: 'NCBI bird genomes',
    tag: 'main',
  },
  {
    id: 'fish',
    title: 'UCSC GenArk - Fish',
    description: 'NCBI fish genomes',
    tag: 'main',
  },
  {
    id: 'vertebrate',
    title: 'UCSC GenArk - Vertebrate',
    description: 'NCBI vertebrate genomes',
    tag: 'main',
  },
  {
    id: 'invertebrate',
    title: 'UCSC GenArk - Invertebrate',
    description: 'NCBI invertebrate genomes',
    tag: 'main',
  },
  {
    id: 'fungi',
    title: 'UCSC GenArk - Fungi',
    description: 'NCBI fungi genomes',
    tag: 'main',
  },
  {
    id: 'plants',
    title: 'UCSC GenArk - Plants',
    description: 'NCBI plant genomes',
    tag: 'main',
  },
  {
    id: 'viral',
    title: 'UCSC GenArk - Viral',
    description: 'NCBI viral genomes',
    tag: 'main',
  },
  {
    id: 'bacteria',
    title: 'UCSC GenArk - Bacteria',
    description: 'NCBI bacteria genomes',
    tag: 'main',
  },
  {
    id: 'archaea',
    title: 'UCSC GenArk - Archaea',
    description: 'NCBI archaea genomes',
    tag: 'main',
  },
  {
    id: 'VGP',
    title: 'UCSC GenArk - VGP (Vertebrate Genomes Project)',
    description: 'Vertebrate Genome Project',
    tag: 'other',
  },
  {
    id: 'CCGP',
    title: 'UCSC GenArk - CCGP (California Conservation Genomics Project)',
    description: 'The California Conservation Genomics Project',
    tag: 'other',
  },
  {
    id: 'HPRC',
    title: 'UCSC GenArk - HPRC (Human Pangenome Reference Consortium)',
    description: 'Human Pangenome Reference Consortium',
    tag: 'other',
  },
  {
    id: 'BRC',
    title: 'UCSC GenArk - BRC (includes VEuPathDB)',
    description:
      'BRC Analytics - Bioinformatics Research Center (VEuPathDB and others)',
    tag: 'other',
  },
  {
    id: 'globalReference',
    title: 'UCSC GenArk - Global Human Reference genomes',
    description: 'Global Human Reference genomes, January 2020',
    tag: 'other',
  },
  {
    id: 'legacy',
    title: 'UCSC GenArk - Legacy (NCBI genomes superseded by newer versions)',
    description: 'NCBI genomes legacy/superseded by newer versions',
    tag: 'other',
  },
]
