#!/usr/bin/env node
/* global window, document -- page.evaluate() bodies run in the browser, not here */
//
// checkConfigCompat.mjs
//
// Loads the configs we actually ship into a matrix of historical JBrowse builds
// and asserts each one still boots. The hub configs live at ONE permanent url
// each (jbrowse.org/ucsc/hg19/config.json), named by desktop installs and
// published links we do not control, so a config we regenerate has to keep
// working on hosts far older than the one we develop against. Nothing told us
// when that stopped being true; this does.
//
// Every release is hosted at jbrowse.org/code/jb2/<version>/, so the matrix
// needs no local install per version.
//
// What counts as a failure, in order of severity:
//   - the app renders its error page instead of a session (fatal: an unknown
//     track type throws out of config hydration, and a plugin url that fails to
//     load rejects PluginLoader's Promise.all, which fails the whole session)
//   - a plugin named by the config did not define its global
//   - fewer tracks are readable than the config declares
//
// Usage:
//   node scripts/checkConfigCompat.mjs                      # full matrix
//   node scripts/checkConfigCompat.mjs --floor v3.7.0       # fail below floor
//   node scripts/checkConfigCompat.mjs --configs hg19,hg38
//   node scripts/checkConfigCompat.mjs --local              # working tree, not
//                                                          # what is published
//
// --local is the pre-upload gate run.sh uses: it feeds the hosted app the
// config files sitting in the working tree, so a regeneration that would break
// a released host is caught while the damage is still local. Without it the
// same matrix reports on what production is serving right now, which is what
// the scheduled canary wants.
//
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parseArgs } from 'node:util'

// puppeteer-core, not puppeteer: this repo builds configs and has no other
// browser need, so it should not carry a ~150MB Chromium download in every
// install. Point CHROME_PATH at a browser, or let it find a system Chrome or a
// puppeteer cache one.
import { launch } from 'puppeteer-core'

function findChrome() {
  const candidates = [
    process.env.CHROME_PATH,
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    ...fs
      .globSync(
        path.join(os.homedir(), '.cache/puppeteer/chrome/*/chrome-*/chrome'),
      )
      .sort()
      .reverse(),
  ].filter(Boolean)
  const found = candidates.find(c => fs.existsSync(c))
  if (!found) {
    throw new Error(
      `no browser found; set CHROME_PATH. Looked in: ${candidates.join(', ')}`,
    )
  }
  return found
}

// The oldest host we intend the shipped configs to keep working on, and every
// release boundary between it and now. Add a version here when it is published;
// remove one only when we deliberately drop support for it.
//
// v2.15.0, v3.0.0 and v3.7.0 were dropped deliberately on 2026-07-30. They were
// already failing and not on anything we ship: v2/v3 could not load the MsaView
// bundle at all, and v3.7.0's mobx-state-tree rejects a FeatureTrack union in the
// config content. Keeping them listed meant the canary reported a permanently
// broken state every 6h, which is how an alert gets ignored. v4.0.0 is the floor.
const HOST_VERSIONS = ['v4.0.0', 'v4.2.0', 'v4.3.0', 'latest', 'main']

// Representative shipped configs: the two most-linked UCSC assemblies, a GenArk
// hub (the sharded path, generated by a different pipeline), and the merge API
// (which composes hub configs at request time, so it can fail on its own).
//
// `local` is the working-tree file that gets uploaded to `url`. With --local we
// serve those bytes to the hosted app instead of what production currently has,
// which is what lets run.sh gate an upload on configs that are not public yet.
// The merge config is composed by a lambda, so it has no local counterpart.
const CONFIGS = {
  hg19: {
    url: 'https://jbrowse.org/ucsc/hg19/config.json',
    local: 'ucsc2jbrowse/configs/hg19.json',
  },
  hg38: {
    url: 'https://jbrowse.org/ucsc/hg38/config.json',
    local: 'ucsc2jbrowse/configs/hg38.json',
  },
  'hg38-minimal': {
    url: 'https://jbrowse.org/ucsc/hg38/minimal.json',
    local: 'ucsc2jbrowse/configs-minimal/hg38.json',
  },
  genark: {
    url: 'https://jbrowse.org/hubs/genark/GCF/000/298/275/GCF_000298275.1/config.json',
    local: 'hubs/GCF/000/298/275/GCF_000298275.1/config.json',
  },
  merge: {
    url: 'https://0hifvzakej.execute-api.us-east-1.amazonaws.com/merge?hubIds=GCF_000001405.40',
  },
}

const { values } = parseArgs({
  options: {
    floor: { type: 'string' },
    configs: { type: 'string' },
    versions: { type: 'string' },
    json: { type: 'string' },
    timeout: { type: 'string', default: '60000' },
    local: { type: 'boolean', default: false },
    plugin: { type: 'string', multiple: true, default: [] },
  },
})

// --plugin Hubs=dist/bundle.js swaps a candidate build in for the bundle a
// config names, on real hosted releases. A plugin bundle reaches every already
// published config the moment it lands (the store uploads `latest/` no-cache),
// so "does this build error-page the app" has to be answerable BEFORE publish,
// not after. Verifying the built umd rather than the source is the point: the
// failure mode is a runtime throw from configure(), which no amount of type
// checking in the plugin repo can rule out.
const pluginOverrides = new Map(
  values.plugin.map(spec => {
    const eq = spec.indexOf('=')
    if (eq < 0) {
      throw new Error(`--plugin wants Name=path, got "${spec}"`)
    }
    return [spec.slice(0, eq), fs.readFileSync(spec.slice(eq + 1), 'utf8')]
  }),
)

const versions = values.versions?.split(',') ?? HOST_VERSIONS
const configNames = values.configs?.split(',') ?? Object.keys(CONFIGS)
const timeout = Number(values.timeout)

// Plugins the host bundles into its own build. jbrowse-web drops a config entry
// naming one of these before loading it (PluginLoader's `vendoredPluginNames`),
// so its UMD global is legitimately absent and its capability is present anyway
// — the seam that lets an old config keep naming a plugin that has since been
// absorbed into core. Keep in step with that set; a name missing here reads as a
// failed plugin load.
const VENDORED_BY_HOST = new Set(['MafViewer', 'GWAS'])

async function declaredContent(url, localBody) {
  const config = localBody
    ? JSON.parse(localBody)
    : await fetch(url).then(res => res.json())
  return {
    plugins: config.plugins ?? [],
    trackCount: config.tracks?.length ?? 0,
    pluginGlobals: (config.plugins ?? [])
      .filter(p => !VENDORED_BY_HOST.has(p.name))
      .map(p => `JBrowsePlugin${p.name}`),
    vendored: (config.plugins ?? [])
      .filter(p => VENDORED_BY_HOST.has(p.name))
      .map(p => p.name),
    trackTypes: [...new Set((config.tracks ?? []).map(t => t.type))],
  }
}

async function probe(browser, hostVersion, configUrl, declared, localBody) {
  const page = await browser.newPage()
  const errors = []
  page.on('pageerror', e => {
    errors.push(String(e).slice(0, 200))
  })
  // Serve the working-tree config in place of the published one, leaving every
  // other request alone. The config keeps its production url, so the ~600 file
  // paths it names relatively still resolve against jbrowse.org and the probe
  // exercises real data — only the config document itself is substituted.
  // Same mechanism for candidate plugin builds: match the url this config
  // declares for that plugin name and answer with the local bundle.
  const bundleSwaps = new Map(
    declared.plugins
      .filter(p => pluginOverrides.has(p.name))
      .map(p => [p.url, pluginOverrides.get(p.name)]),
  )
  if (localBody !== undefined || bundleSwaps.size > 0) {
    await page.setRequestInterception(true)
    page.on('request', request => {
      const url = request.url()
      if (localBody !== undefined && url === configUrl) {
        request.respond({
          status: 200,
          contentType: 'application/json',
          headers: { 'access-control-allow-origin': '*' },
          body: localBody,
        })
      } else if (bundleSwaps.has(url)) {
        request.respond({
          status: 200,
          contentType: 'text/javascript',
          headers: { 'access-control-allow-origin': '*' },
          body: bundleSwaps.get(url),
        })
      } else {
        request.continue()
      }
    })
  }
  const app = `https://jbrowse.org/code/jb2/${hostVersion}/`
  const result = { hostVersion, configUrl }
  try {
    await page.goto(`${app}?config=${encodeURIComponent(configUrl)}`, {
      waitUntil: 'domcontentloaded',
      timeout: 60_000,
    })
    // Readiness is the session global (set by jbrowse-web since v1.0.1, so it
    // is available across this whole matrix) or the error page — NOT the
    // presence of any element: the loading spinner is an svg, so waiting on
    // markup returns before plugins have loaded and reads every host as broken.
    result.settled = await page
      .waitForFunction(
        () =>
          !!(
            /** @type {Record<string, any>} */
            (window).JBrowseSession ??
            /** @type {Record<string, any>} */ (window).__jbrowse_session
          ) ||
          /JBrowse Error|Fatal error|Failed to load/.test(
            document.body.innerText,
          ),
        { timeout },
      )
      .then(() => true)
      .catch(() => false)

    result.fatal = await page.evaluate(() => {
      const t = document.body.innerText
      return /JBrowse Error|Fatal error|Failed to load/.test(t)
        ? t.replace(/\s+/g, ' ').slice(0, 240)
        : undefined
    })

    result.missingPluginGlobals = await page.evaluate(
      globals => globals.filter(g => !(g in window)),
      declared.pluginGlobals,
    )

    // Track count as the host itself sees it, so a config the host silently
    // truncates (rather than throwing on) is still caught.
    result.readableTracks = await page.evaluate(() => {
      const w = /** @type {Record<string, any>} */ (window)
      const session = w.JBrowseSession ?? w.__jbrowse_session
      return session?.tracks?.length ?? session?.jbrowse?.tracks?.length
    })
  } catch (e) {
    result.threw = String(e).slice(0, 200)
  }
  result.pageErrors = [...new Set(errors)].slice(0, 4)
  await page.close()
  return result
}

const browser = await launch({
  headless: true,
  executablePath: findChrome(),
  args: ['--no-sandbox', '--use-gl=swiftshader'],
  defaultViewport: { width: 1400, height: 900 },
})

const results = []
let failed = false
for (const name of configNames) {
  const entry = CONFIGS[name]
  if (!entry) {
    throw new Error(`unknown config "${name}"`)
  }
  const { url: configUrl } = entry
  // In --local mode a config with no working-tree counterpart is skipped rather
  // than silently probed against production, which would read as a pass for
  // something the gate never actually checked.
  if (values.local && !entry.local) {
    console.log(`\n${name}: skipped, composed remotely (no local counterpart)`)
    continue
  }
  const localBody =
    values.local && entry.local
      ? fs.readFileSync(
          path.join(import.meta.dirname, '..', entry.local),
          'utf8',
        )
      : undefined
  const declared = await declaredContent(configUrl, localBody)
  console.log(
    `\n${name}${localBody === undefined ? '' : ' (working tree)'}: ` +
      `${declared.trackCount} tracks, ${declared.pluginGlobals.length} plugins` +
      (declared.vendored.length > 0
        ? ` (+${declared.vendored.join(', ')} vendored by newer hosts)`
        : ''),
  )
  for (const hostVersion of versions) {
    const r = await probe(browser, hostVersion, configUrl, declared, localBody)
    r.config = name
    results.push(r)
    const problems = [
      r.fatal && `FATAL ${r.fatal}`,
      r.threw && `threw ${r.threw}`,
      !r.settled && !r.fatal && 'never settled (no session, no error page)',
      r.missingPluginGlobals?.length > 0 &&
        `plugins did not load: ${r.missingPluginGlobals.join(', ')}`,
      r.readableTracks !== undefined &&
        r.readableTracks < declared.trackCount &&
        `only ${r.readableTracks}/${declared.trackCount} tracks readable`,
    ].filter(Boolean)
    console.log(
      `  ${hostVersion.padEnd(10)} ${problems.length > 0 ? problems.join(' | ') : 'ok'}`,
    )
    const atOrAboveFloor =
      !values.floor ||
      versions.indexOf(hostVersion) >= versions.indexOf(values.floor)
    if (problems.length > 0 && atOrAboveFloor) {
      failed = true
    }
  }
}
await browser.close()

if (values.json) {
  fs.writeFileSync(values.json, JSON.stringify(results, null, 2))
}

if (failed) {
  console.error(
    `\nA shipped config broke on a host at or above the ${values.floor ?? 'oldest tested'} floor.`,
  )
  process.exit(1)
}
