#!/usr/bin/env node
/* global window, document -- page.evaluate() bodies run in the browser, not here */
//
// checkConfigCompat.mjs
//
// Loads the configs we actually ship into a matrix of historical JBrowse builds
// and asserts each one still boots. The hub configs live at ONE permanent url
// each (jbrowse.org/ucsc/hg19/config.json), named by desktop installs and
// published links we do not control, so a config we regenerate has to keep
// working on hosts far older than the one we develop against. Nothing told us
// when that stopped being true; this does.
//
// Every release is hosted at jbrowse.org/code/jb2/<version>/, so the matrix
// needs no local install per version.
//
// What counts as a failure, in order of severity:
//   - the app renders its error page instead of a session (fatal: an unknown
//     track type throws out of config hydration, and a plugin url that fails to
//     load rejects PluginLoader's Promise.all, which fails the whole session)
//   - a plugin named by the config did not define its global
//   - fewer tracks are readable than the config declares
//   - (--offline-ucsc only) the assembly never loaded, so the session's view
//     has no displayedRegions
//
// Usage:
//   node scripts/checkConfigCompat.mjs                      # full matrix
//   node scripts/checkConfigCompat.mjs --floor v3.7.0       # fail below floor
//   node scripts/checkConfigCompat.mjs --configs hg19,hg38
//   node scripts/checkConfigCompat.mjs --local              # working tree, not
//                                                          # what is published
//   node scripts/checkConfigCompat.mjs --offline-ucsc       # UCSC outage drill
//
// --offline-ucsc aborts every request to the hgdownload family and asserts
// hg38/hg19 still open. See OFFLINE_HOSTS and offlineDefaults below for what
// that does and does not prove.
//
// --local is the pre-upload gate run.sh uses: it feeds the hosted app the
// config files sitting in the working tree, so a regeneration that would break
// a released host is caught while the damage is still local. Without it the
// same matrix reports on what production is serving right now, which is what
// the scheduled canary wants.
//
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { parseArgs } from 'node:util'

// puppeteer-core, not puppeteer: this repo builds configs and has no other
// browser need, so it should not carry a ~150MB Chromium download in every
// install. Point CHROME_PATH at a browser, or let it find a system Chrome or a
// puppeteer cache one.
import { launch } from 'puppeteer-core'

import { resolveBuiltDir } from './builtDir.mjs'

function findChrome() {
  const candidates = [
    process.env.CHROME_PATH,
    '/usr/bin/google-chrome',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    ...fs
      .globSync(
        path.join(os.homedir(), '.cache/puppeteer/chrome/*/chrome-*/chrome'),
      )
      .sort()
      .reverse(),
  ].filter(Boolean)
  const found = candidates.find(c => fs.existsSync(c))
  if (!found) {
    throw new Error(
      `no browser found; set CHROME_PATH. Looked in: ${candidates.join(', ')}`,
    )
  }
  return found
}

// The oldest host we intend the shipped configs to keep working on, and every
// release boundary between it and now. Add a version here when it is published;
// remove one only when we deliberately drop support for it.
//
// v2.15.0, v3.0.0 and v3.7.0 were dropped deliberately on 2026-07-30. They were
// already failing and not on anything we ship: v2/v3 could not load the MsaView
// bundle at all, and v3.7.0's mobx-state-tree rejects a FeatureTrack union in the
// config content. Keeping them listed meant the canary reported a permanently
// broken state every 6h, which is how an alert gets ignored. v4.0.0 is the floor.
const HOST_VERSIONS = ['v4.0.0', 'v4.2.0', 'v4.3.0', 'latest', 'main']

// Representative shipped configs: the two most-linked UCSC assemblies, a GenArk
// hub (the sharded path, generated by a different pipeline), and the merge API
// (which composes hub configs at request time, so it can fail on its own).
//
// `local` is the working-tree file that gets uploaded to `url`. With --local we
// serve those bytes to the hosted app instead of what production currently has,
// which is what lets run.sh gate an upload on configs that are not public yet.
// The merge config is composed by a lambda, so it has no local counterpart.
const CONFIGS = {
  hg19: {
    url: 'https://jbrowse.org/ucsc/hg19/config.json',
    local: 'ucsc2jbrowse/configs/hg19.json',
  },
  hg38: {
    url: 'https://jbrowse.org/ucsc/hg38/config.json',
    local: 'ucsc2jbrowse/configs/hg38.json',
  },
  'hg38-minimal': {
    url: 'https://jbrowse.org/ucsc/hg38/minimal.json',
    local: 'ucsc2jbrowse/configs-minimal/hg38.json',
  },
  genark: {
    url: 'https://jbrowse.org/hubs/genark/GCF/000/298/275/GCF_000298275.1/config.json',
    local: 'hubs/GCF/000/298/275/GCF_000298275.1/config.json',
  },
  merge: {
    url: 'https://0hifvzakej.execute-api.us-east-1.amazonaws.com/merge?hubIds=GCF_000001405.40',
  },
  // mergeAll's output: 239 assemblies, ~11k tracks and the one plugin list that
  // is a union rather than a copy. That list is why it is worth booting at all
  // -- plugins[].url is the only field that can kill a whole session, and
  // mergeAll used to emit the same four plugins three times over under
  // different urls, so PluginLoader's Promise.all was installing 12. It is also
  // 26MB, which is the reason it is not in ALL_JSON_VERSIONS' full matrix.
  all: {
    url: 'https://jbrowse.org/ucsc/all.json',
    // `built`, not `local`: mergeAll writes all.json into $UCSC_BUILT_DIR and
    // nothing mirrors it into the repo, so --local can only reach it on the
    // build machine. Where it is absent this is skipped, which is honest --
    // and the canary boots the published copy either way.
    built: 'all.json',
  },
}

// all.json alone is skipped on the intermediate releases. Its 26MB parse is
// most of this script's wall clock, and what it adds over hg38 is the merged
// plugin list, which is config content and identical on every host. Floor plus
// latest is where a plugin-loading regression would actually show.
const ALL_JSON_VERSIONS = new Set([HOST_VERSIONS[0], 'latest'])

const { values } = parseArgs({
  options: {
    floor: { type: 'string' },
    'built-dir': { type: 'string' },
    configs: { type: 'string' },
    versions: { type: 'string' },
    json: { type: 'string' },
    timeout: { type: 'string', default: '60000' },
    local: { type: 'boolean', default: false },
    'offline-ucsc': { type: 'boolean', default: false },
    plugin: { type: 'string', multiple: true, default: [] },
  },
})

const offline = values['offline-ucsc']

// The UCSC outage drill. Every request whose host starts with `hgdownload` is
// aborted, and the assertion is that hg38 and hg19 still open — which is the
// property assembly sidecar mirroring buys (ADR 0003) and which no other check
// covers: check-sidecar-urls proves a config NAMES local files, not that the
// app opens without upstream.
//
// Two things this deliberately does NOT claim:
//
//   - It is not the real outage. hgdownload fails by STALLING — the TCP
//     handshake completes, the TLS Client Hello goes out, and no Server Hello
//     comes back — and jbrowse-core sets no fetch deadline, so the real symptom
//     is a session that hangs forever. request.abort() fails fast instead. That
//     makes this a test of config content (does loadPre() touch only files we
//     serve) rather than a reproduction of the hang. UcscStatusBanner is the
//     part that addresses the hang, and it lives in the website.
//   - It says nothing about GenArk, which is deliberately not mirrored: those
//     configs name hgdownload for both chromSizes and refNameAliases, so a
//     GenArk assembly is expected to fail this and is not in the default set.
//
// The whole hgdownload family, not just the one spelling the configs use today.
// hgdownload2.soe.ucsc.edu is a byte-identical mirror on a different UCSC
// address block and hgdownload.gi.ucsc.edu is another alias for the same
// service — all three go down with the same file server, so a config that
// quietly switched to a sibling name would otherwise pass a drill proving
// nothing. genome.ucsc.edu and api.genome.ucsc.edu are NOT blocked: they are a
// different host that answered normally through the stall we measured, and the
// configs reference them only from trackDb prose, which the browser never
// fetches.
const isUcscFileServer = url => {
  try {
    const { hostname } = new URL(url)
    return hostname.startsWith('hgdownload') && hostname.endsWith('.ucsc.edu')
  } catch {
    return false
  }
}

// --plugin Hubs=dist/bundle.js swaps a candidate build in for the bundle a
// config names, on real hosted releases. A plugin bundle reaches every already
// published config the moment it lands (the store uploads `latest/` no-cache),
// so "does this build error-page the app" has to be answerable BEFORE publish,
// not after. Verifying the built umd rather than the source is the point: the
// failure mode is a runtime throw from configure(), which no amount of type
// checking in the plugin repo can rule out.
const pluginOverrides = new Map(
  values.plugin.map(spec => {
    const eq = spec.indexOf('=')
    if (eq < 0) {
      throw new Error(`--plugin wants Name=path, got "${spec}"`)
    }
    return [spec.slice(0, eq), fs.readFileSync(spec.slice(eq + 1), 'utf8')]
  }),
)

// The drill's default matrix is the floor plus `latest`, not all five hosts: a
// 6-hourly cron that boots the whole matrix offline as well as online doubles
// the canary's cost, and the property under test is config content, which is
// the same document on every host. The floor earns its slot anyway because the
// one host-side half of this IS version-sensitive — a relative `chromSizes`
// resolves only because jbrowse-web stamps `baseUri` beside the adapter's uri
// and TwoBitAdapter's preProcessSnapshot forwards it, and v4.0.0 is the oldest
// build we make that promise on. `main` is left out: it is the dev host, the
// online matrix already covers it, and its breakage is not a support promise.
const OFFLINE_VERSIONS = [HOST_VERSIONS[0], 'latest']

// The two most-linked UCSC assemblies, and the two of checkSidecarUrls.mjs's
// MUST_BE_LOCAL set that CONFIGS already carries. mm39, mm10 and hs1 make the
// same promise and are not drilled: MUST_BE_LOCAL already fails the pre-upload
// gate if any of the five regresses to naming an upstream sidecar, so what this
// adds on top is the app-behaviour half, and paying for that on two assemblies
// every 6h buys most of the signal. Add one here if that stops feeling true.
const OFFLINE_CONFIGS = ['hg38', 'hg19']

const versions =
  values.versions?.split(',') ?? (offline ? OFFLINE_VERSIONS : HOST_VERSIONS)
const configNames =
  values.configs?.split(',') ??
  (offline ? OFFLINE_CONFIGS : Object.keys(CONFIGS))
const timeout = Number(values.timeout)

// Plugins the host bundles into its own build. jbrowse-web drops a config entry
// naming one of these before loading it (PluginLoader's `vendoredPluginNames`),
// so its UMD global is legitimately absent and its capability is present anyway
// — the seam that lets an old config keep naming a plugin that has since been
// absorbed into core. Keep in step with that set; a name missing here reads as a
// failed plugin load.
const VENDORED_BY_HOST = new Set(['MafViewer', 'GWAS'])

async function declaredContent(url, localBody) {
  const config = localBody
    ? JSON.parse(localBody)
    : await fetch(url).then(res => res.json())
  return {
    plugins: config.plugins ?? [],
    trackCount: config.tracks?.length ?? 0,
    pluginGlobals: (config.plugins ?? [])
      .filter(p => !VENDORED_BY_HOST.has(p.name))
      .map(p => `JBrowsePlugin${p.name}`),
    vendored: (config.plugins ?? [])
      .filter(p => VENDORED_BY_HOST.has(p.name))
      .map(p => p.name),
    trackTypes: [...new Set((config.tracks ?? []).map(t => t.type))],
  }
}

async function probe(browser, hostVersion, configUrl, declared, localBody) {
  const page = await browser.newPage()
  const errors = []
  page.on('pageerror', e => {
    errors.push(String(e).slice(0, 200))
  })
  // Serve the working-tree config in place of the published one, leaving every
  // other request alone. The config keeps its production url, so the ~600 file
  // paths it names relatively still resolve against jbrowse.org and the probe
  // exercises real data — only the config document itself is substituted.
  // Same mechanism for candidate plugin builds: match the url this config
  // declares for that plugin name and answer with the local bundle.
  const bundleSwaps = new Map(
    declared.plugins
      .filter(p => pluginOverrides.has(p.name))
      .map(p => [p.url, pluginOverrides.get(p.name)]),
  )
  let blockedRequests = 0
  if (localBody !== undefined || bundleSwaps.size > 0 || offline) {
    await page.setRequestInterception(true)
    page.on('request', request => {
      const url = request.url()
      if (offline && isUcscFileServer(url)) {
        blockedRequests += 1
        request.abort()
      } else if (localBody !== undefined && url === configUrl) {
        request.respond({
          status: 200,
          contentType: 'application/json',
          headers: { 'access-control-allow-origin': '*' },
          body: localBody,
        })
      } else if (bundleSwaps.has(url)) {
        request.respond({
          status: 200,
          contentType: 'text/javascript',
          headers: { 'access-control-allow-origin': '*' },
          body: bundleSwaps.get(url),
        })
      } else {
        request.continue()
      }
    })
  }
  const app = `https://jbrowse.org/code/jb2/${hostVersion}/`
  const result = { hostVersion, configUrl }
  try {
    await page.goto(`${app}?config=${encodeURIComponent(configUrl)}`, {
      waitUntil: 'domcontentloaded',
      timeout: 60_000,
    })
    // Readiness is the session global (set by jbrowse-web since v1.0.1, so it
    // is available across this whole matrix) or the error page — NOT the
    // presence of any element: the loading spinner is an svg, so waiting on
    // markup returns before plugins have loaded and reads every host as broken.
    result.settled = await page
      .waitForFunction(
        () =>
          !!(
            /** @type {Record<string, any>} */
            (window).JBrowseSession ??
            /** @type {Record<string, any>} */ (window).__jbrowse_session
          ) ||
          /JBrowse Error|Fatal error|Failed to load/.test(
            document.body.innerText,
          ),
        { timeout },
      )
      .then(() => true)
      .catch(() => false)

    result.fatal = await page.evaluate(() => {
      const t = document.body.innerText
      return /JBrowse Error|Fatal error|Failed to load/.test(t)
        ? t.replace(/\s+/g, ' ').slice(0, 240)
        : undefined
    })

    result.missingPluginGlobals = await page.evaluate(
      globals => globals.filter(g => !(g in window)),
      declared.pluginGlobals,
    )

    // Track count as the host itself sees it, so a config the host silently
    // truncates (rather than throwing on) is still caught.
    result.readableTracks = await page.evaluate(() => {
      const w = /** @type {Record<string, any>} */ (window)
      const session = w.JBrowseSession ?? w.__jbrowse_session
      return session?.tracks?.length ?? session?.jbrowse?.tracks?.length
    })

    if (offline) {
      // "Still opens" needs an assertion the other checks cannot make. A failed
      // assembly renders no error page, defines every plugin global and leaves
      // the track count intact, so fatal/plugins/tracks all report ok while the
      // session is unusable — ADR 0003 says as much. What an outage actually
      // takes away is loadPre(): the assembly's regions never arrive, so the
      // defaultSession's view never gets its displayedRegions. Wait for those.
      result.viewRegions = await page
        .waitForFunction(
          () => {
            const w = /** @type {Record<string, any>} */ (window)
            const session = w.JBrowseSession ?? w.__jbrowse_session
            return session?.views?.[0]?.displayedRegions?.length > 0
          },
          { timeout },
        )
        .then(() => true)
        .catch(() => false)

      // assemblyManager keeps the rejection rather than throwing it, so read it
      // out: "loadPre failed on hg38.chromAlias.txt" is a far better report
      // than "the view has no regions".
      result.assemblyErrors = await page.evaluate(() => {
        const w = /** @type {Record<string, any>} */ (window)
        const session = w.JBrowseSession ?? w.__jbrowse_session
        try {
          return (session?.assemblyManager?.assemblies ?? [])
            .filter(a => a.error)
            .map(a => `${a.name}: ${String(a.error).slice(0, 160)}`)
        } catch {
          return []
        }
      })
    }
  } catch (e) {
    result.threw = String(e).slice(0, 200)
  }
  result.pageErrors = [...new Set(errors)].slice(0, 4)
  result.blockedRequests = blockedRequests
  await page.close()
  return result
}

const browser = await launch({
  headless: true,
  executablePath: findChrome(),
  args: ['--no-sandbox', '--use-gl=swiftshader'],
  defaultViewport: { width: 1400, height: 900 },
})

if (offline) {
  console.log(
    'UCSC outage drill: aborting every request to hgdownload*.ucsc.edu.\n' +
      'The real outage stalls rather than failing, so this tests whether the ' +
      'configs\nname only files we serve, not the hang itself.',
  )
}

const results = []
let failed = false
for (const name of configNames) {
  const entry = CONFIGS[name]
  if (!entry) {
    throw new Error(`unknown config "${name}"`)
  }
  const { url: configUrl } = entry
  // In --local mode a config with no working-tree counterpart is skipped rather
  // than silently probed against production, which would read as a pass for
  // something the gate never actually checked.
  const builtDir = entry.built
    ? resolveBuiltDir(values['built-dir'])
    : undefined
  const builtPath =
    builtDir === undefined ? undefined : path.join(builtDir, entry.built)
  const localPath = entry.local
    ? path.join(import.meta.dirname, '..', entry.local)
    : builtPath !== undefined && fs.existsSync(builtPath)
      ? builtPath
      : undefined
  if (values.local && localPath === undefined) {
    console.log(
      `\n${name}: skipped, ${entry.built ? 'not in the built tree here' : 'composed remotely'} (no local counterpart)`,
    )
    continue
  }
  const localBody =
    values.local && localPath !== undefined
      ? fs.readFileSync(localPath, 'utf8')
      : undefined
  const declared = await declaredContent(configUrl, localBody)
  console.log(
    `\n${name}${localBody === undefined ? '' : ' (working tree)'}: ` +
      `${declared.trackCount} tracks, ${declared.pluginGlobals.length} plugins` +
      (declared.vendored.length > 0
        ? ` (+${declared.vendored.join(', ')} vendored by newer hosts)`
        : ''),
  )
  // Honour an explicit --versions; the narrowing is a default, not a rule.
  const configVersions =
    name === 'all' && values.versions === undefined
      ? versions.filter(v => ALL_JSON_VERSIONS.has(v))
      : versions
  for (const hostVersion of configVersions) {
    const r = await probe(browser, hostVersion, configUrl, declared, localBody)
    r.config = name
    results.push(r)
    const problems = [
      r.fatal && `FATAL ${r.fatal}`,
      r.threw && `threw ${r.threw}`,
      !r.settled && !r.fatal && 'never settled (no session, no error page)',
      r.missingPluginGlobals?.length > 0 &&
        `plugins did not load: ${r.missingPluginGlobals.join(', ')}`,
      r.readableTracks !== undefined &&
        r.readableTracks < declared.trackCount &&
        `only ${r.readableTracks}/${declared.trackCount} tracks readable`,
      offline &&
        r.viewRegions === false &&
        'assembly never loaded: the view got no displayedRegions with ' +
          'hgdownload blocked',
      offline &&
        r.assemblyErrors?.length > 0 &&
        `assembly error: ${r.assemblyErrors.join('; ')}`,
    ].filter(Boolean)
    // The blocked count is reported, never failed on. Zero is the ideal result
    // -- the whole page load touched hgdownload not once -- but it is also what
    // a misconfigured predicate looks like, so print it rather than asserting
    // either way on it.
    const suffix = offline ? ` [${r.blockedRequests} blocked]` : ''
    console.log(
      `  ${hostVersion.padEnd(10)} ${problems.length > 0 ? problems.join(' | ') : 'ok'}${suffix}`,
    )
    const atOrAboveFloor =
      !values.floor ||
      versions.indexOf(hostVersion) >= versions.indexOf(values.floor)
    if (problems.length > 0 && atOrAboveFloor) {
      failed = true
    }
  }
}
await browser.close()

if (values.json) {
  fs.writeFileSync(values.json, JSON.stringify(results, null, 2))
}

if (failed) {
  console.error(
    offline
      ? '\nUCSC outage drill FAILED: an assembly we promise stays open with ' +
          'hgdownload unreachable did not open. Check that finalizeConfigs.ts ' +
          'still mirrors the sidecars (see check-sidecar-urls and ADR 0003).'
      : `\nA shipped config broke on a host at or above the ${values.floor ?? 'oldest tested'} floor.`,
  )
  process.exit(1)
}
