import { Suspense, lazy, useEffect, useState } from 'react'

import ProteinDomainCartoon from './ProteinDomainCartoon.tsx'
import {
  type GeneStructure,
  type InlineMsa,
  buildSessionUrl,
  fetchGeneStructure,
  geneStats,
} from './geneStructure.ts'
import { COMMON_SPECIES } from './orthologSearchUtils.ts'
import {
  type ProteinAlignment,
  type ProteinPanel,
  alignProteinPanel,
  assembleProteinPanel,
} from './proteinMsa.ts'
import { loadJsonOnce } from '../lib/fetchJson.ts'

// react-msaview pulls in @jbrowse/core + MUI + mobx and renders to canvas, so it
// only runs client-side; lazy-loading keeps it off the first paint and out of
// the cartoon/genome path until the user opens the full alignment.
const MSAViewer = lazy(() =>
  import('react-msaview').then(m => ({ default: m.MSAViewer })),
)

// Textbook multi-domain genes, present across the model organisms and covered
// by the precomputed cache below, so every example is instant end-to-end.
const EXAMPLES = ['TP53', 'BRCA2', 'EGFR', 'SOD1']

// Precomputed panel + alignment for the example genes (generated by
// generateProteinExamples.ts), keyed by `${SYMBOL}:${refTaxId}`. Lets a chip
// click render the cartoon and the full alignment with no NCBI/EBI wait.
interface CachedExample {
  panel: ProteinPanel
  alignment: ProteinAlignment
}

// Optional precomputed cache: a load failure just means examples resolve live,
// so degrade to an empty map rather than surfacing an error.
function loadExampleCache(): Promise<Record<string, CachedExample>> {
  return loadJsonOnce<Record<string, CachedExample>>(
    '/proteinExamples.json',
  ).catch((): Record<string, CachedExample> => ({}))
}

const cacheKey = (symbol: string, ref: number) =>
  `${symbol.trim().toUpperCase()}:${ref}`

// client:only island, so window is available for the shareable ?gene=&ref= link.
function paramsFromUrl() {
  const p = new URLSearchParams(window.location.search)
  const ref = Number(p.get('ref'))
  return { gene: p.get('gene')?.trim() ?? '', ref: ref > 0 ? ref : 9606 }
}

export default function ProteinBrowser() {
  const [gene, setGene] = useState(() => paramsFromUrl().gene)
  const [taxId, setTaxId] = useState(() => paramsFromUrl().ref)
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState('')
  const [error, setError] = useState('')
  const [structure, setStructure] = useState<GeneStructure | null>(null)
  const [collapse, setCollapse] = useState(true)
  const [panel, setPanel] = useState<ProteinPanel | null>(null)
  // Precomputed alignment for an example gene, used to skip EBI when the user
  // asks for the full alignment.
  const [precomputed, setPrecomputed] = useState<ProteinAlignment | null>(null)
  const [alignment, setAlignment] = useState<ProteinAlignment | null>(null)
  const [aligning, setAligning] = useState(false)

  // Phase 1: the gene's own genome/AlphaFold structure and the ortholog domain
  // panel, resolved together. Example genes take the panel side from the
  // precomputed cache instantly; everything else resolves live from NCBI.
  const run = async (query: string, ref: number) => {
    const sym = query.trim()
    if (sym) {
      setGene(sym)
      setTaxId(ref)
      setError('')
      setStructure(null)
      setPanel(null)
      setPrecomputed(null)
      setAlignment(null)
      const params = new URLSearchParams({ gene: sym, ref: String(ref) })
      window.history.replaceState(null, '', `?${params.toString()}`)
      setLoading(true)
      try {
        const cached = (await loadExampleCache())[cacheKey(sym, ref)]
        const [structureResult, panelResult] = await Promise.all([
          fetchGeneStructure(sym, ref),
          cached
            ? Promise.resolve(cached.panel)
            : assembleProteinPanel(sym, ref, { onProgress: setStatus }),
        ])
        setStructure(structureResult)
        setPanel(panelResult)
        if (cached) {
          setPrecomputed(cached.alignment)
        }
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
      } finally {
        setLoading(false)
      }
    }
  }

  // Phase 2: the full alignment (EBI Clustal Omega, with CDD domains). Built
  // once and shared: it drives the embedded react-msaview panel below and
  // rides along in the JBrowse session as a connected MsaView.
  const buildAlignment = async (p: ProteinPanel) => {
    if (precomputed) {
      setAlignment(precomputed)
    } else {
      setAligning(true)
      setError('')
      try {
        setAlignment(await alignProteinPanel(p, { onProgress: setStatus }))
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
      } finally {
        setAligning(false)
      }
    }
  }

  useEffect(() => {
    if (gene) {
      void run(gene, taxId)
    }
  }, [])

  const found = new Set(panel?.rows.map(r => r.taxId))
  const missing = COMMON_SPECIES.filter(s => !found.has(s.taxId))
  const queryRow =
    panel && (panel.rows.find(r => r.taxId === taxId) ?? panel.rows[0])
  const inlineMsa: InlineMsa | undefined =
    alignment && queryRow
      ? {
          fasta: alignment.fasta,
          newick: alignment.newick,
          gff: alignment.gff,
          querySeqName: queryRow.label,
        }
      : undefined

  return (
    <div>
      <div className="msv-form">
        <input
          value={gene}
          onChange={e => {
            setGene(e.target.value)
          }}
          onKeyDown={e => {
            if (e.key === 'Enter') {
              void run(gene, taxId)
            }
          }}
          placeholder="Gene symbol, e.g. TP53"
          disabled={loading}
        />
        <select
          value={taxId}
          onChange={e => {
            setTaxId(Number(e.target.value))
          }}
          disabled={loading}
        >
          {COMMON_SPECIES.map(s => (
            <option
              key={s.taxId}
              value={s.taxId}
            >
              {s.label}
            </option>
          ))}
        </select>
        <button
          onClick={() => {
            void run(gene, taxId)
          }}
          disabled={loading || !gene.trim()}
        >
          {loading ? 'Resolving…' : 'Explore'}
        </button>
      </div>

      <div className="msv-examples">
        <span>Examples:</span>
        {EXAMPLES.map(g => (
          <button
            key={g}
            className="msv-example-chip"
            disabled={loading}
            onClick={() => {
              void run(g, taxId)
            }}
          >
            {g}
          </button>
        ))}
      </div>

      <p className="msv-scope">
        The domain cartoon and alignment compare one representative protein
        (MANE Select, else longest isoform) per species across{' '}
        {COMMON_SPECIES.length} model organisms — human through yeast and
        plants. Not a general species search.
      </p>

      {loading && <p className="msv-hint">{status || 'Resolving…'}</p>}
      {error && <p className="msv-error">{error}</p>}

      {panel && !loading && (
        <>
          <p className="msv-hint">
            {panel.rows.length} of {COMMON_SPECIES.length} model species ·{' '}
            <a
              href={`/orthologs?gene=${encodeURIComponent(panel.query.symbol)}&ref=${panel.query.refTaxonId}`}
            >
              ortholog table
            </a>{' '}
            ·{' '}
            <a
              href={`/conserved-gene-order?gene=${encodeURIComponent(panel.query.symbol)}&ref=${panel.query.refTaxonId}`}
            >
              conserved gene order
            </a>
          </p>
          {missing.length > 0 && (
            <p className="msv-note">
              No annotated ortholog in: {missing.map(s => s.label).join(', ')}
            </p>
          )}

          <ProteinDomainCartoon rows={panel.rows} />

          {alignment ? (
            <Suspense
              fallback={<p className="msv-hint">Loading alignment viewer…</p>}
            >
              <MSAViewer
                msa={alignment.fasta}
                tree={alignment.newick}
                gff={alignment.gff}
                colorScheme="clustalx_protein_dynamic"
                height={520}
              />
            </Suspense>
          ) : (
            <div className="msv-advanced">
              <button
                className="msv-advanced-btn"
                disabled={aligning}
                onClick={() => {
                  void buildAlignment(panel)
                }}
              >
                {aligning
                  ? status || 'Aligning…'
                  : 'Add cross-species alignment'}
              </button>
              <span className="msv-advanced-note">
                Residue-level alignment + guide tree, overlaid with the domains
                above and added to the JBrowse session below
                {precomputed
                  ? ' (precomputed)'
                  : ' — via EBI Clustal Omega, can take up to a minute'}
                .
              </span>
            </div>
          )}
        </>
      )}

      {structure && !loading && (
        <ResultCard
          structure={structure}
          collapse={collapse}
          onToggleCollapse={setCollapse}
          inlineMsa={inlineMsa}
        />
      )}
    </div>
  )
}

function ResultCard({
  structure,
  collapse,
  onToggleCollapse,
  inlineMsa,
}: {
  structure: GeneStructure
  collapse: boolean
  onToggleCollapse: (v: boolean) => void
  inlineMsa: InlineMsa | undefined
}) {
  const { transcript, assemblyAccession, uniprotId } = structure
  const { codingBp, ratio } = geneStats(transcript)
  const { url } = buildSessionUrl({ structure, collapse, inlineMsa })
  const alignRows = inlineMsa
    ? (inlineMsa.fasta.match(/^>/gm) ?? []).length
    : undefined
  const chips = [
    `${transcript.cds.length} coding exons`,
    `${codingBp.toLocaleString()} bp CDS`,
    `${ratio}× collapsed`,
    alignRows ? `${alignRows}-species alignment` : undefined,
    uniprotId ? 'AlphaFold structure' : undefined,
  ].filter((c): c is string => !!c)

  return (
    <div className="msv-result">
      <h2>
        {transcript.geneName} <span className="msv-sub">{transcript.name}</span>
      </h2>
      <p className="msv-meta">
        {assemblyAccession} · {transcript.refName}{' '}
        {transcript.strand === 1 ? '+' : '−'}
      </p>
      <div className="msv-chips">
        {chips.map(c => (
          <span
            key={c}
            className="msv-chip"
          >
            {c}
          </span>
        ))}
      </div>

      <div className="msv-actions">
        <a
          className="msv-open"
          href={url}
          target="_blank"
          rel="noopener noreferrer"
        >
          Open in JBrowse ↗
        </a>
        <label className="msv-collapse">
          <input
            type="checkbox"
            checked={collapse}
            onChange={e => {
              onToggleCollapse(e.target.checked)
            }}
          />
          Collapse introns
        </label>
      </div>

      <p className="msv-note">
        {inlineMsa
          ? `Cross-species alignment (${alignRows} species) included — connected to the genome and structure.`
          : 'Add the cross-species alignment above to include it in this session.'}
      </p>
    </div>
  )
}
