import '../styles/ui.css'

import { useState } from 'react'

import useSWRImmutable from 'swr/immutable'

import { loadJsonOnce } from '../lib/fetchJson.ts'
import { LIVE_QUERY } from '../lib/swr.ts'
import ErrorMessage from './ErrorMessage.tsx'
import GeneCombobox from './GeneCombobox.tsx'
import HelpButton from './HelpButton.tsx'
import ProteinAlignmentSection, {
  type AlignSource,
  loadHundredWay,
  loadLive,
} from './ProteinAlignmentSection.tsx'
import { HelpDialog } from './ProteinBrowserDialogs.tsx'
import ProteinDomainCartoon from './ProteinDomainCartoon.tsx'
import ProteinLaunchCard from './ProteinLaunchCard.tsx'
import { examplesFor } from './geneExamples.ts'
import { fetchOrthologSymbol } from './geneSearch.ts'
import { type GeneStructure, fetchGeneStructure } from './geneStructure.ts'
import { hasHundredWay } from './hundredWay.ts'
import { COMMON_SPECIES, geneUrl, syncGeneUrl } from './orthologSearchUtils.ts'
import {
  type Domain,
  type ProteinAlignment,
  type ProteinPanel,
  alignedRows,
  assembleProteinPanel,
  canAlign,
} from './proteinMsa.ts'

// Precomputed panel + alignment for the example genes (generated by
// generateBroadPanel.ts), keyed by `${SYMBOL}:${refTaxId}`. Lets a chip click
// render the cartoon and the full alignment with no NCBI/EBI wait.
//
// The alignment half stays optional in the type because the generator's survey
// mode (no --align) writes the panel alone. What the shipped file actually holds
// is the other arrangement: every entry has its alignment, and none of them has
// sequences — see `usable`. A chip with no entry here is not a broken chip: it
// resolves live, on the same defaults the generator used.
interface CachedExample {
  panel: ProteinPanel
  alignment?: ProteinAlignment
}

// Optional precomputed cache: a load failure just means examples resolve live,
// so degrade to an empty map rather than surfacing an error.
function loadExampleCache(): Promise<Record<string, CachedExample>> {
  return loadJsonOnce<Record<string, CachedExample>>(
    '/proteinExamples.json',
  ).catch((): Record<string, CachedExample> => ({}))
}

// An entry that shipped its alignment has had the sequences stripped out from
// under it. An entry with neither is the one shape that cannot serve: it would
// draw the cartoon and then fail the alignment on a precondition the reader can
// do nothing about, so it is ignored rather than trusted.
function usable(entry: CachedExample | undefined) {
  return entry && (entry.alignment || canAlign(entry.panel)) ? entry : undefined
}

// The generator and this lookup share one spelling rule, so a chip for any
// species finds its entry however the symbol was typed.
export const cacheKey = (symbol: string, ref: number) =>
  `${symbol.trim().toUpperCase()}:${ref}`

// client:only island, so window is available for the shareable ?gene=&ref= link.
function paramsFromUrl() {
  const p = new URLSearchParams(window.location.search)
  const ref = Number(p.get('ref'))
  const known = COMMON_SPECIES.some(s => s.taxId === ref)
  return { gene: p.get('gene')?.trim() ?? '', ref: known ? ref : 9606 }
}

function message(e: unknown) {
  return e instanceof Error ? e.message : String(e)
}

type PanelOutcome = { panel: ProteinPanel } | { panelError: string }

interface Resolved {
  structure: GeneStructure
  panel: PanelOutcome
  // the precomputed alignment for an example gene, used to skip EBI
  precomputed?: ProteinAlignment
  // whether this gene has a row in the hosted 100-way alignment
  hundredWay: boolean
}

// Phase 1: the gene's own genome/structure, then the ortholog domain panel.
// Example genes take the panel side from the precomputed cache instantly;
// everything else resolves live.
//
// The structure comes FIRST so its resolved GeneID can seed the panel: ncbiFetch
// serializes every request, so running them concurrently would not overlap them
// anyway, and the structure's id is the gene NCBI actually places on an
// assembly. The 100-way index is not an NCBI read, so it does overlap.
//
// A failed panel is NOT fatal. The genome view and the structure come from the
// structure half alone, and they are worth having even when no ortholog set
// covers the gene — which is exactly the case on the species where ortholog
// coverage is thinnest.
async function resolveGene(
  sym: string,
  ref: number,
  onProgress: (s: string) => void,
): Promise<Resolved> {
  const cached = usable((await loadExampleCache())[cacheKey(sym, ref)])
  const structure = await fetchGeneStructure(sym, ref)
  // keyed on NCBI's canonical spelling of the symbol, which is what the hosted
  // index uses — a typed "tp53" would otherwise miss
  const hundredWayPending = hasHundredWay(structure.symbol, ref)
  const panel = await (
    cached
      ? Promise.resolve(cached.panel)
      : assembleProteinPanel(sym, ref, { onProgress, geneId: structure.geneId })
  ).then(
    (panel): PanelOutcome => ({ panel }),
    (e: unknown): PanelOutcome => ({ panelError: message(e) }),
  )
  return {
    structure,
    panel,
    precomputed: cached?.alignment,
    hundredWay: await hundredWayPending,
  }
}

export default function ProteinBrowser() {
  // The submitted query, as opposed to what is currently in the boxes: it is the
  // SWR key, so it changes only on Explore/Enter/an example chip. Seeded from the
  // page url, which is what makes a shared ?gene=&ref= link resolve on mount —
  // this island is client:only, so window is readable during the first render.
  const [query, setQuery] = useState(paramsFromUrl)
  const [gene, setGene] = useState(query.gene)
  const [taxId, setTaxId] = useState(query.ref)
  const [status, setStatus] = useState('')
  const [helpOpen, setHelpOpen] = useState(false)

  const {
    data,
    error,
    isLoading: loading,
  } = useSWRImmutable(
    query.gene ? (['protein-gene', query.gene, query.ref] as const) : null,
    ([, sym, ref]) => resolveGene(sym, ref, setStatus),
    LIVE_QUERY,
  )

  const run = (rawQuery: string, ref: number) => {
    const sym = rawQuery.trim()
    if (sym) {
      setGene(sym)
      setTaxId(ref)
      setQuery({ gene: sym, ref })
      syncGeneUrl(sym, ref)
    }
  }

  // Symbols do not carry across organisms, so a species switch follows NCBI's
  // ortholog to the new species rather than re-running a symbol that means
  // nothing there. Nothing to follow (or no ortholog) just changes the species.
  const switchSpecies = (ref: number) => {
    setTaxId(ref)
    const geneId = data?.structure.geneId
    if (geneId && query.gene) {
      setStatus('Following the ortholog…')
      void fetchOrthologSymbol(geneId, ref).then(symbol => {
        setStatus('')
        if (symbol) {
          run(symbol, ref)
        }
      })
    }
  }

  const examples = examplesFor(taxId)

  return (
    <div>
      <div className="ui-form">
        <GeneCombobox
          value={gene}
          taxId={taxId}
          disabled={loading}
          onChange={v => {
            setGene(v)
          }}
          onSubmit={symbol => {
            run(symbol, taxId)
          }}
        />
        <select
          className="ui-select"
          value={taxId}
          onChange={e => {
            switchSpecies(Number(e.target.value))
          }}
          disabled={loading}
          aria-label="Reference organism"
        >
          {COMMON_SPECIES.map(s => (
            <option
              key={s.taxId}
              value={s.taxId}
            >
              {s.label}
            </option>
          ))}
        </select>
        <button
          className="ui-btn"
          onClick={() => {
            run(gene, taxId)
          }}
          disabled={loading || !gene.trim()}
        >
          {loading ? 'Resolving…' : 'Explore'}
        </button>
        <HelpButton
          label="How the protein browser works"
          onClick={() => {
            setHelpOpen(true)
          }}
        />
      </div>

      <div className="msv-examples">
        <span>Examples:</span>
        {examples.map(ex => (
          <button
            key={ex.symbol}
            className="ui-chip-btn"
            title={ex.note}
            disabled={loading}
            onClick={() => {
              run(ex.symbol, taxId)
            }}
          >
            {ex.symbol}
          </button>
        ))}
      </div>

      {loading && <p className="ui-hint">{status || 'Resolving…'}</p>}
      <ErrorMessage
        error={error}
        className="ui-error"
      />

      {data && (
        // Remounted per query, which is what drops a previous gene's alignment
        // request, superposition picks and domain selection without an effect.
        <GeneResults
          key={`${query.gene}:${query.ref}`}
          {...data}
          taxId={query.ref}
          status={status}
          onProgress={setStatus}
        />
      )}

      {helpOpen && (
        <HelpDialog
          onClose={() => {
            setHelpOpen(false)
          }}
        />
      )}
    </div>
  )
}

// Everything downstream of a resolved gene. The page is a launcher, so the
// session card leads with the one primary action and the two heavy views — the
// domain cartoon and the alignment — fold away underneath it. The alignment
// still loads while its disclosure is closed, because it is what the launched
// session carries.
function GeneResults({
  structure,
  panel: panelOutcome,
  precomputed,
  hundredWay,
  taxId,
  status,
  onProgress,
}: Resolved & {
  taxId: number
  status: string
  onProgress: (s: string) => void
}) {
  const { symbol } = structure
  const panel = 'panel' in panelOutcome ? panelOutcome.panel : undefined
  // The 100-way is one indexed read, so where it exists it is the better first
  // impression: 100 vertebrates with no wait, against a Clustal Omega job. The
  // live panel keeps the domain overlay, which is why both are offered.
  const [source, setSource] = useState<AlignSource>(
    hundredWay ? 'hundredWay' : 'live',
  )
  // The live alignment is the only one worth gating behind a click — it costs an
  // EBI job. The 100-way loads as soon as it is chosen.
  const [wantLive, setWantLive] = useState(false)
  const wantAlignment = source === 'hundredWay' || wantLive
  // Swiss-Prot accessions of the ortholog rows marked for superposition, and
  // the query-row domain the session should open on.
  const [superposed, setSuperposed] = useState<string[]>([])
  const [selectedDomain, setSelectedDomain] = useState<Domain>()

  const {
    data: alignment,
    error,
    isLoading: aligning,
  } = useSWRImmutable(
    wantAlignment
      ? (['protein-alignment', symbol, taxId, source] as const)
      : null,
    ([, sym, , src]) =>
      src === 'hundredWay'
        ? loadHundredWay(sym)
        : loadLive(panel!, precomputed, onProgress),
    LIVE_QUERY,
  )

  const toggleSuperpose = (uniprot: string) => {
    setSuperposed(
      superposed.includes(uniprot)
        ? superposed.filter(u => u !== uniprot)
        : [...superposed, uniprot],
    )
  }

  return (
    <>
      <ProteinLaunchCard
        structure={structure}
        alignment={alignment}
        superposed={
          panel
            ? panel.rows.filter(
                r => r.uniprot && superposed.includes(r.uniprot),
              )
            : []
        }
        onRemoveSuperposed={u => {
          toggleSuperpose(u)
        }}
        queryRow={panel?.rows.find(r => r.taxId === panel.query.refTaxonId)}
        selectedDomain={selectedDomain}
        onClearDomain={() => {
          setSelectedDomain(undefined)
        }}
      />

      {'panelError' in panelOutcome && (
        <p className="ui-note">
          No ortholog panel for {symbol}: {panelOutcome.panelError}
        </p>
      )}
      {panel && (
        <DomainSection
          panel={panel}
          selectedDomain={selectedDomain}
          onSelectDomain={d => {
            setSelectedDomain(
              selectedDomain &&
                selectedDomain.name === d.name &&
                selectedDomain.start === d.start
                ? undefined
                : d,
            )
          }}
          superposed={superposed}
          onToggleSuperpose={u => {
            toggleSuperpose(u)
          }}
        />
      )}

      {(hundredWay || panel) && (
        <ProteinAlignmentSection
          gene={symbol}
          alignment={alignment}
          error={error}
          aligning={aligning}
          status={status}
          source={source}
          onSource={s => {
            setSource(s)
          }}
          bothSources={hundredWay && !!panel}
          panelRows={panel ? alignedRows(panel).length : 0}
          precomputed={!!precomputed}
          wantLive={wantLive}
          onBuildLive={() => {
            setWantLive(true)
          }}
        />
      )}

      <p className="ui-hint">
        <a href={geneUrl('/orthologs', symbol, taxId)}>Ortholog table</a> ·{' '}
        <a href={geneUrl('/conserved-gene-order', symbol, taxId)}>
          Conserved gene order
        </a>
      </p>
    </>
  )
}

// The cartoon, and the species it could not cover. Folded away because it
// answers a question the reader has after the launch rather than before it.
function DomainSection({
  panel,
  selectedDomain,
  onSelectDomain,
  superposed,
  onToggleSuperpose,
}: {
  panel: ProteinPanel
  selectedDomain: Domain | undefined
  onSelectDomain: (d: Domain) => void
  superposed: string[]
  onToggleSuperpose: (uniprot: string) => void
}) {
  const found = new Set(panel.rows.map(r => r.taxId))
  // The panel asks its source for every species it has, so a model organism
  // absent from a short panel really has no ortholog on record and is worth
  // naming. On a full panel the same list is noise — it would name the four
  // invertebrates under 60 vertebrates on nearly every gene.
  const short = panel.rows.length <= COMMON_SPECIES.length
  const missing = short ? COMMON_SPECIES.filter(s => !found.has(s.taxId)) : []
  // "60 of 658" rather than a bare 60: a capped panel should say so.
  const total = panel.query.total
  return (
    <details className="ui-disclosure">
      <summary>
        Domain architecture{' '}
        <span className="ui-caption">
          {panel.rows.length} species
          {total && total > panel.rows.length ? ` of ${total}` : ''}
        </span>
      </summary>
      <ProteinDomainCartoon
        rows={panel.rows}
        queryTaxId={panel.query.refTaxonId}
        selectedDomain={selectedDomain}
        onSelectDomain={onSelectDomain}
        superposed={superposed}
        onToggleSuperpose={onToggleSuperpose}
      />
      {missing.length > 0 && (
        <p className="ui-note">
          No ortholog in {missing.map(s => s.label).join(', ')}
        </p>
      )}
    </details>
  )
}
