import { Suspense, lazy, useEffect, useRef, useState } from 'react'

import useSWRImmutable from 'swr/immutable'

import { loadJsonOnce } from '../lib/fetchJson.ts'
import { LIVE_QUERY } from '../lib/swr.ts'
import ErrorMessage from './ErrorMessage.tsx'
import ProteinDomainCartoon from './ProteinDomainCartoon.tsx'
import { HelpDialog, SessionDetailsDialog } from './ProteinBrowserDialogs.tsx'
import { examplesFor } from './geneExamples.ts'
import { fetchOrthologSymbol, searchGenes } from './geneSearch.ts'
import {
  type GeneStructure,
  type IndexedMsa,
  type InlineMsa,
  buildSessionUrl,
  fetchGeneStructure,
  geneStats,
} from './geneStructure.ts'
import {
  HUNDRED_WAY_MSA,
  HUNDRED_WAY_TREE,
  fetchHundredWayAlignment,
  fetchHundredWayTranscript,
  hasHundredWay,
} from './hundredWay.ts'
import { COMMON_SPECIES, geneUrl, syncGeneUrl } from './orthologSearchUtils.ts'
import {
  type ProteinAlignment,
  type ProteinPanel,
  alignProteinPanel,
  assembleProteinPanel,
} from './proteinMsa.ts'

// react-msaview pulls in @jbrowse/core + MUI + mobx and renders to canvas, so it
// only runs client-side; lazy-loading keeps it off the first paint and out of
// the cartoon/genome path until there is an alignment to draw.
const MSAViewer = lazy(() =>
  import('react-msaview').then(m => ({ default: m.MSAViewer })),
)

// Precomputed panel + alignment for the example genes (generated by
// generateProteinExamples.ts), keyed by `${SYMBOL}:${refTaxId}`. Lets a chip
// click render the cartoon and the full alignment with no NCBI/EBI wait.
interface CachedExample {
  panel: ProteinPanel
  alignment: ProteinAlignment
}

// Optional precomputed cache: a load failure just means examples resolve live,
// so degrade to an empty map rather than surfacing an error.
function loadExampleCache(): Promise<Record<string, CachedExample>> {
  return loadJsonOnce<Record<string, CachedExample>>(
    '/proteinExamples.json',
  ).catch((): Record<string, CachedExample> => ({}))
}

const cacheKey = (symbol: string, ref: number) =>
  `${symbol.trim().toUpperCase()}:${ref}`

// client:only island, so window is available for the shareable ?gene=&ref= link.
function paramsFromUrl() {
  const p = new URLSearchParams(window.location.search)
  const ref = Number(p.get('ref'))
  return { gene: p.get('gene')?.trim() ?? '', ref: ref > 0 ? ref : 9606 }
}

function message(e: unknown) {
  return e instanceof Error ? e.message : String(e)
}

interface Resolved {
  structure: GeneStructure
  panel?: ProteinPanel
  panelError?: string
  // the precomputed alignment for an example gene, used to skip EBI
  precomputed?: ProteinAlignment
  // whether this gene has a row in the hosted 100-way alignment
  hundredWay: boolean
}

// Phase 1: the gene's own genome/AlphaFold structure and the ortholog domain
// panel, resolved together. Example genes take the panel side from the
// precomputed cache instantly; everything else resolves live.
//
// A failed panel is NOT fatal. The genome view and the AlphaFold structure come
// from the structure half alone, and they are worth having even when no ortholog
// set covers the gene — which is exactly the case on the species where ortholog
// coverage is thinnest.
async function resolveGene(
  sym: string,
  ref: number,
  onProgress: (s: string) => void,
): Promise<Resolved> {
  const cached = (await loadExampleCache())[cacheKey(sym, ref)]
  const panelPromise = cached
    ? Promise.resolve(cached.panel)
    : assembleProteinPanel(sym, ref, { onProgress })
  const [structure, panelOutcome] = await Promise.all([
    fetchGeneStructure(sym, ref),
    panelPromise.then(
      panel => ({ panel }),
      (e: unknown) => ({ panelError: message(e) }),
    ),
  ])
  return {
    structure,
    ...panelOutcome,
    precomputed: cached?.alignment,
    // keyed on NCBI's canonical spelling of the symbol, which is what the
    // hosted index uses — a typed "tp53" would otherwise miss
    hundredWay: await hasHundredWay(structure.symbol, ref),
  }
}

export default function ProteinBrowser() {
  // The submitted query, as opposed to what is currently in the boxes: it is the
  // SWR key, so it changes only on Explore/Enter/an example chip. Seeded from the
  // page url, which is what makes a shared ?gene=&ref= link resolve on mount —
  // this island is client:only, so window is readable during the first render.
  const [query, setQuery] = useState(paramsFromUrl)
  const [gene, setGene] = useState(query.gene)
  const [taxId, setTaxId] = useState(query.ref)
  const [status, setStatus] = useState('')
  const [helpOpen, setHelpOpen] = useState(false)

  const {
    data,
    error,
    isLoading: loading,
  } = useSWRImmutable(
    query.gene ? (['protein-gene', query.gene, query.ref] as const) : null,
    ([, sym, ref]) => resolveGene(sym, ref, setStatus),
    LIVE_QUERY,
  )

  const run = (rawQuery: string, ref: number) => {
    const sym = rawQuery.trim()
    if (sym) {
      setGene(sym)
      setTaxId(ref)
      setQuery({ gene: sym, ref })
      syncGeneUrl(sym, ref)
    }
  }

  // Symbols do not carry across organisms, so a species switch follows NCBI's
  // ortholog to the new species rather than re-running a symbol that means
  // nothing there. Nothing to follow (or no ortholog) just changes the species.
  const switchSpecies = (ref: number) => {
    setTaxId(ref)
    const geneId = data?.structure.geneId
    if (geneId && query.gene) {
      setStatus('Following the ortholog…')
      void fetchOrthologSymbol(geneId, ref).then(symbol => {
        setStatus('')
        if (symbol) {
          run(symbol, ref)
        }
      })
    }
  }

  const examples = examplesFor(taxId)

  return (
    <div>
      <div className="msv-form">
        <GeneCombobox
          value={gene}
          taxId={taxId}
          disabled={loading}
          onChange={setGene}
          onSubmit={symbol => {
            run(symbol, taxId)
          }}
        />
        <select
          value={taxId}
          onChange={e => {
            switchSpecies(Number(e.target.value))
          }}
          disabled={loading}
          aria-label="Reference organism"
        >
          {COMMON_SPECIES.map(s => (
            <option
              key={s.taxId}
              value={s.taxId}
            >
              {s.label}
            </option>
          ))}
        </select>
        <button
          onClick={() => {
            run(gene, taxId)
          }}
          disabled={loading || !gene.trim()}
        >
          {loading ? 'Resolving…' : 'Explore'}
        </button>
        <button
          className="msv-icon-btn"
          title="How the protein browser works"
          aria-label="How the protein browser works"
          onClick={() => {
            setHelpOpen(true)
          }}
        >
          ?
        </button>
      </div>

      <div className="msv-examples">
        <span>Examples:</span>
        {examples.map(ex => (
          <button
            key={ex.symbol}
            className="msv-example-chip"
            title={ex.note}
            disabled={loading}
            onClick={() => {
              run(ex.symbol, taxId)
            }}
          >
            {ex.symbol}
          </button>
        ))}
      </div>

      <p className="msv-scope">
        The domain cartoon and alignment compare one representative protein
        (MANE Select, else longest isoform) per species across{' '}
        {COMMON_SPECIES.length} model organisms — human through yeast and
        plants. Not a general species search.
      </p>

      {loading && <p className="msv-hint">{status || 'Resolving…'}</p>}
      <ErrorMessage
        error={error}
        className="msv-error"
      />

      {data && (
        // Remounted per query, which is what drops a previous gene's alignment
        // request back to the cartoon without an effect to reset it.
        <GeneResults
          key={`${query.gene}:${query.ref}`}
          {...data}
          taxId={query.ref}
          status={status}
          onProgress={setStatus}
        />
      )}

      {helpOpen && (
        <HelpDialog
          onClose={() => {
            setHelpOpen(false)
          }}
        />
      )}
    </div>
  )
}

// A gene-symbol box with suggestions. Deliberately free-text: Enter submits what
// was typed unless a suggestion is highlighted, so a symbol the type-ahead has
// not heard of (or has not answered for yet) still runs. The suggestions are a
// convenience; NCBI decides whether the gene exists.
function GeneCombobox({
  value,
  taxId,
  disabled,
  onChange,
  onSubmit,
}: {
  value: string
  taxId: number
  disabled: boolean
  onChange: (v: string) => void
  onSubmit: (v: string) => void
}) {
  const [hits, setHits] = useState<string[]>([])
  const [open, setOpen] = useState(false)
  const [highlighted, setHighlighted] = useState(-1)
  // what the user typed, as opposed to a symbol put in the box by a chip or a
  // species switch — only typing should fire a lookup
  const [typed, setTyped] = useState('')
  const boxRef = useRef<HTMLDivElement>(null)

  // Debounced and race-safe: the cleanup drops a slow earlier response so it
  // cannot land on top of a newer one.
  useEffect(() => {
    if (typed.trim().length < 2) {
      setHits([])
      return
    }
    let ignore = false
    const timer = setTimeout(() => {
      void searchGenes(typed.trim(), taxId).then(found => {
        // set even when empty, so a no-match query clears stale suggestions
        if (!ignore) {
          setHits(found)
          setHighlighted(-1)
        }
      })
    }, 220)
    return () => {
      ignore = true
      clearTimeout(timer)
    }
  }, [typed, taxId])

  useEffect(() => {
    function onDocMouseDown(e: MouseEvent) {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', onDocMouseDown)
    return () => {
      document.removeEventListener('mousedown', onDocMouseDown)
    }
  }, [])

  const choose = (symbol: string) => {
    onChange(symbol)
    setTyped('')
    setOpen(false)
    onSubmit(symbol)
  }

  const showList = open && hits.length > 0 && !disabled

  return (
    <div
      className="msv-combobox"
      ref={boxRef}
    >
      <input
        value={value}
        role="combobox"
        aria-expanded={showList}
        aria-controls="msv-gene-listbox"
        aria-autocomplete="list"
        autoComplete="off"
        placeholder="Gene symbol, e.g. TP53"
        disabled={disabled}
        onChange={e => {
          onChange(e.target.value)
          setTyped(e.target.value)
          setOpen(true)
        }}
        onFocus={() => {
          setOpen(true)
        }}
        onKeyDown={e => {
          if (e.key === 'ArrowDown' && showList) {
            e.preventDefault()
            setHighlighted(i => Math.min(i + 1, hits.length - 1))
          } else if (e.key === 'ArrowUp' && showList) {
            e.preventDefault()
            setHighlighted(i => Math.max(i - 1, -1))
          } else if (e.key === 'Enter') {
            e.preventDefault()
            const picked = showList ? hits[highlighted] : undefined
            choose(picked ?? value)
          } else if (e.key === 'Escape') {
            setOpen(false)
          }
        }}
      />
      {showList && (
        <ul
          className="msv-listbox"
          id="msv-gene-listbox"
          role="listbox"
        >
          {hits.map((symbol, i) => (
            <li
              key={symbol}
              role="option"
              aria-selected={i === highlighted}
              className={i === highlighted ? 'msv-option highlighted' : 'msv-option'}
              onMouseEnter={() => {
                setHighlighted(i)
              }}
              onMouseDown={e => {
                // mousedown, not click: the document listener above closes the
                // list on mousedown and the click would never arrive
                e.preventDefault()
                choose(symbol)
              }}
            >
              {symbol}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// Which alignment the page shows and the session carries.
type AlignSource = 'live' | 'hundredWay'

interface LoadedAlignment {
  inline?: InlineMsa
  indexed?: IndexedMsa
  // what the embedded viewer renders
  fasta: string
  newick?: string
  treeUri?: string
  gff?: string
  rowCount: number
  // for the 100-way, the knownCanonical model the alignment was built from —
  // swapped into the session so genome, alignment and structure share codons
  structureOverrides?: Partial<GeneStructure>
}

// Everything downstream of a resolved gene: the domain cartoon, the alignment
// (from whichever source is selected), and the JBrowse session card.
function GeneResults({
  structure,
  panel,
  panelError,
  precomputed,
  hundredWay,
  taxId,
  status,
  onProgress,
}: Resolved & {
  taxId: number
  status: string
  onProgress: (s: string) => void
}) {
  const { symbol } = structure
  const [collapse, setCollapse] = useState(true)
  const [flip, setFlip] = useState(structure.transcript.strand === -1)
  // The 100-way is one indexed read, so where it exists it is the better first
  // impression: 100 vertebrates with no wait, against a Clustal Omega job. The
  // live panel keeps the domain overlay, which is why both are offered.
  const [source, setSource] = useState<AlignSource>(
    hundredWay ? 'hundredWay' : 'live',
  )
  // The live alignment is the only one worth gating behind a click — it costs an
  // EBI job. The 100-way loads as soon as it is chosen.
  const [wantLive, setWantLive] = useState(false)
  const wantAlignment = source === 'hundredWay' || wantLive

  const {
    data: alignment,
    error,
    isLoading: aligning,
  } = useSWRImmutable(
    wantAlignment ? (['protein-alignment', symbol, taxId, source] as const) : null,
    ([, sym, , src]) =>
      src === 'hundredWay'
        ? loadHundredWay(sym)
        : loadLive(panel!, precomputed, onProgress),
    LIVE_QUERY,
  )

  const found = new Set(panel?.rows.map(r => r.taxId))
  const missing = COMMON_SPECIES.filter(s => !found.has(s.taxId))

  return (
    <>
      <p className="msv-hint">
        {panel
          ? `${panel.rows.length} of ${COMMON_SPECIES.length} model species · `
          : ''}
        <a href={geneUrl('/orthologs', symbol, taxId)}>ortholog table</a> ·{' '}
        <a href={geneUrl('/conserved-gene-order', symbol, taxId)}>
          conserved gene order
        </a>
      </p>
      {panelError && (
        <p className="msv-note">
          No cross-species panel for {symbol}: {panelError}. The genome view and
          structure below still work.
        </p>
      )}
      {panel && missing.length > 0 && (
        <p className="msv-note">
          No annotated ortholog in: {missing.map(s => s.label).join(', ')}
        </p>
      )}

      {panel && <ProteinDomainCartoon rows={panel.rows} />}

      {(hundredWay || panel) && (
        <AlignmentSource
          source={source}
          hundredWay={hundredWay}
          live={!!panel}
          precomputed={!!precomputed}
          onChange={next => {
            setSource(next)
          }}
        />
      )}

      <ErrorMessage
        error={error}
        className="msv-error"
      />

      {alignment ? (
        <Suspense
          fallback={<p className="msv-hint">Loading alignment viewer…</p>}
        >
          <MSAViewer
            msa={alignment.fasta}
            {...(alignment.newick ? { tree: alignment.newick } : {})}
            {...(alignment.treeUri
              ? {
                  treeFilehandle: {
                    uri: alignment.treeUri,
                    locationType: 'UriLocation',
                  },
                }
              : {})}
            {...(alignment.gff ? { gff: alignment.gff } : {})}
            colorScheme="clustalx_protein_dynamic"
            treeAreaWidth={200}
            height={520}
          />
        </Suspense>
      ) : source === 'live' && panel ? (
        <div className="msv-advanced">
          <button
            className="msv-advanced-btn"
            disabled={aligning}
            onClick={() => {
              setWantLive(true)
            }}
          >
            {aligning ? status || 'Aligning…' : 'Build cross-species alignment'}
          </button>
          <span className="msv-advanced-note">
            Residue-level alignment + guide tree, overlaid with the domains
            above and added to the JBrowse session below
            {precomputed
              ? ' (precomputed)'
              : ' — via EBI Clustal Omega, can take up to a minute'}
            .
          </span>
        </div>
      ) : aligning ? (
        <p className="msv-hint">Reading the 100-way alignment…</p>
      ) : null}

      <ResultCard
        structure={structure}
        alignment={alignment}
        collapse={collapse}
        onToggleCollapse={setCollapse}
        flip={flip}
        onToggleFlip={setFlip}
      />
    </>
  )
}

// The hosted 100-way for one gene: the alignment block, and the transcript it
// was built from so the session's connectedFeature shares its codon ordinals.
async function loadHundredWay(symbol: string): Promise<LoadedAlignment> {
  const [msa, transcript] = await Promise.all([
    fetchHundredWayAlignment(symbol),
    fetchHundredWayTranscript(symbol),
  ])
  if (!msa) {
    throw new Error(`No 100-way alignment row for ${symbol}`)
  }
  return {
    indexed: {
      msaUri: HUNDRED_WAY_MSA,
      treeUri: HUNDRED_WAY_TREE,
      msaName: symbol,
      querySeqName: msa.querySeqName,
    },
    fasta: msa.fasta,
    treeUri: HUNDRED_WAY_TREE,
    rowCount: msa.rowCount,
    structureOverrides: {
      // the aligned hg38 row is the knownCanonical translation, so it is the
      // protein whose residues the alignment's columns count
      proteinSequence: msa.querySequence,
      ...(transcript ? { transcript } : {}),
    },
  }
}

// The live panel aligned at EBI, with the CDD domains as a per-row overlay.
async function loadLive(
  panel: ProteinPanel,
  precomputed: ProteinAlignment | undefined,
  onProgress: (s: string) => void,
): Promise<LoadedAlignment> {
  const aligned = precomputed ?? (await alignProteinPanel(panel, { onProgress }))
  const queryRow =
    panel.rows.find(r => r.taxId === panel.query.refTaxonId) ?? panel.rows[0]!
  return {
    inline: {
      fasta: aligned.fasta,
      newick: aligned.newick,
      gff: aligned.gff,
      querySeqName: queryRow.label,
    },
    fasta: aligned.fasta,
    newick: aligned.newick,
    gff: aligned.gff,
    rowCount: (aligned.fasta.match(/^>/gm) ?? []).length,
  }
}

// The choice between the two alignment sources, shown only where there is a
// choice to make. Each option says what it costs and what it gives up.
function AlignmentSource({
  source,
  hundredWay,
  live,
  precomputed,
  onChange,
}: {
  source: AlignSource
  hundredWay: boolean
  live: boolean
  precomputed: boolean
  onChange: (s: AlignSource) => void
}) {
  if (!hundredWay || !live) {
    return null
  }
  return (
    <div className="msv-source">
      <span className="msv-source-label">Alignment</span>
      <label className="msv-source-option">
        <input
          type="radio"
          name="align-source"
          checked={source === 'hundredWay'}
          onChange={() => {
            onChange('hundredWay')
          }}
        />
        100 vertebrates <span className="msv-source-note">instant, no domains</span>
      </label>
      <label className="msv-source-option">
        <input
          type="radio"
          name="align-source"
          checked={source === 'live'}
          onChange={() => {
            onChange('live')
          }}
        />
        {COMMON_SPECIES.length} model species{' '}
        <span className="msv-source-note">
          with CDD domains{precomputed ? ', precomputed' : ', ~a minute'}
        </span>
      </label>
    </div>
  )
}

function ResultCard({
  structure,
  alignment,
  collapse,
  onToggleCollapse,
  flip,
  onToggleFlip,
}: {
  structure: GeneStructure
  alignment: LoadedAlignment | undefined
  collapse: boolean
  onToggleCollapse: (v: boolean) => void
  flip: boolean
  onToggleFlip: (v: boolean) => void
}) {
  const [detailsOpen, setDetailsOpen] = useState(false)
  // The 100-way carries its own transcript and query protein; swapping them in
  // here is what keeps the launched session's three views on one coordinate
  // space, rather than pairing that alignment with a different isoform.
  const launched = { ...structure, ...alignment?.structureOverrides }
  const { transcript, assemblyAccession, uniprotId } = launched
  const { codingBp, ratio } = geneStats(transcript)
  const { session, url } = buildSessionUrl({
    structure: launched,
    collapse,
    flip,
    inlineMsa: alignment?.inline,
    indexedMsa: alignment?.indexed,
  })
  const chips = [
    `${transcript.cds.length} coding exons`,
    `${codingBp.toLocaleString()} bp CDS`,
    `${ratio}× collapsed`,
    alignment ? `${alignment.rowCount}-species alignment` : undefined,
    uniprotId ? 'AlphaFold structure' : undefined,
    launched.target.geneTrackId ? 'gene track' : undefined,
  ].filter((c): c is string => !!c)

  return (
    <div className="msv-result">
      <h2>
        {transcript.geneName} <span className="msv-sub">{transcript.name}</span>
      </h2>
      <p className="msv-meta">
        {assemblyAccession} · {launched.target.assemblyName} ·{' '}
        {launched.target.canonicalRefName(transcript.refName)}{' '}
        {transcript.strand === 1 ? '+' : '−'}
      </p>
      <div className="msv-chips">
        {chips.map(c => (
          <span
            key={c}
            className="msv-chip"
          >
            {c}
          </span>
        ))}
      </div>

      <div className="msv-actions">
        <a
          className="msv-open"
          href={url}
          target="_blank"
          rel="noopener noreferrer"
        >
          Open in JBrowse ↗
        </a>
        <button
          className="msv-advanced-btn"
          onClick={() => {
            setDetailsOpen(true)
          }}
        >
          Session details
        </button>
      </div>

      <div className="msv-options">
        <label className="msv-collapse">
          <input
            type="checkbox"
            checked={collapse}
            onChange={e => {
              onToggleCollapse(e.target.checked)
            }}
          />
          Collapse introns
        </label>
        {transcript.strand === -1 && (
          <label className="msv-collapse">
            <input
              type="checkbox"
              checked={flip}
              onChange={e => {
                onToggleFlip(e.target.checked)
              }}
            />
            Read 5′→3′
          </label>
        )}
      </div>

      <p className="msv-note">
        {alignment
          ? `Alignment (${alignment.rowCount} species) included — connected to the genome and structure.`
          : 'Add an alignment above to include it in this session.'}
      </p>

      {detailsOpen && (
        <SessionDetailsDialog
          onClose={() => {
            setDetailsOpen(false)
          }}
          transcript={transcript}
          session={session}
          collapse={collapse}
          flip={flip}
          uniprotId={uniprotId}
        />
      )}
    </div>
  )
}
